MMDB with nested structures break read and export FIX
ipinfo/mmdbctl pull request #10
Opened 2023-05-24 22:39 UTC by awaismslm

In this PR, I have fixed the error on nested structure export and read. Please see the following to see how actual `export` and `read` work. 

**Read with ipinfo db:**
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/3fd7a5ca-c848-46a9-9335-facb90d4d23c)

**Read with MaxMind's db:**
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/f004db60-2dc6-452f-96b8-c2387cb6c3b5)
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/fb9aed6d-2baf-44b7-8324-12cf6fa558c1)

**Export with ipinfo db:**
Used [asn.json](https://storage.googleapis.com/ipinfoio/artifacts/v1/asn.json.gz) for this.

JSON:
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/c15cb0b5-7c44-4f0b-ab42-d796dba10c1b)

CSV:
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/804c220b-8d88-42b0-8619-e160d9b2a8d8)

TSV:
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/f5433777-3953-4313-b7bf-b7af4c6ed493)

**Export with MaxMind's db:**

JSON:
`{"continent":{"code":"AF","geoname_id":6255146,"names":{"de":"Afrika","en":"Africa","es":"África","fr":"Afrique","ja":"アフリカ","pt-BR":"África","ru":"Африка","zh-CN":"非洲"}},"country":{"geoname_id":433561,"iso_code":"BI","names":{"de":"Burundi","en":"Burundi","es":"Burundi","fr":"Burundi","ja":"ブルンジ共和国","pt-BR":"Burundi","ru":"Бурунди","zh-CN":"布隆迪"}},"range":"2.18.11.0/24","registered_country":{"geoname_id":2750405,"is_in_european_union":true,"iso_code":"NL","names":{"de":"Niederlande","en":"Netherlands","es":"Holanda","fr":"Pays-Bas","ja":"オランダ王国","pt-BR":"Holanda","ru":"Нидерланды","zh-CN":"荷兰"}}}`
CSV:
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/0b77984e-a953-4c83-aa69-4f9d1ed5f0f6)

TSV:
![image](https://github.com/ipinfo/mmdbctl/assets/109338796/54d1ba89-d6c2-4b16-8fee-78df93534fa6)

I'll spend some more time testing it.

2023-05-25 05:09 UTC, UmanShahzad commented on utils.go
> +		case []interface{}:
If it's an array of items, we can actually JSON marshal that too.

2023-05-25 07:49 UTC, UmanShahzad commented
Are we able to test an mmdb that has an array inside of it to see the behavior there now with the above change?

2023-05-25 08:51 UTC, UmanShahzad commented
Can you show how it would look just for completeness before we merge?

2023-05-25 10:44 UTC, awaismslm commented
Sure, Please see the following. exported to json
`{"asn":"AS13335","domain":"cloudflare.com","name":"Cloudflare, Inc.","network":"1.0.0.0/24","range":"1.0.0.0/24","route":"1.0.0.0/24","type":"**[hosting ffff333 ffff4444]**"}
{"asn":"AS38803","domain":"gtelecom.com.au","name":"Wirefreebroadband Pty Ltd","network":"1.0.4.0/24","range":"1.0.4.0/24","route":"1.0.4.0/22","type":"**[isp ff11 ff22]**"}
`

2023-05-25 10:48 UTC, UmanShahzad commented
Hmm ok that looks problematic - it is creating a string version of the array in the final json output. My understanding was if we export to JSON, then the embedded objects/arrays will come out as proper objects/arrays. For CSV/TSV they would come out as JSON-ified json representations.

2023-05-25 11:06 UTC, awaismslm commented
> Hmm ok that looks problematic - it is creating a string version of the array in the final json output. My understanding was if we export to JSON, then the embedded objects/arrays will come out as proper objects/arrays. For CSV/TSV they would come out as JSON-ified json representations.

The issue is with the import of nested structures. Below json is generated after import fix.
`{"asn":"AS13335","domain":"cloudflare.com","name":"Cloudflare, Inc.","network":"1.0.0.0/24","range":"1.0.0.0/24","route":"1.0.0.0/24","type":"[\"hosting\",\"ffff333\",\"ffff4444\"]"}
{"asn":"AS38803","domain":"gtelecom.com.au","name":"Wirefreebroadband Pty Ltd","network":"1.0.4.0/24","range":"1.0.4.0/24","route":"1.0.4.0/22","type":"[\"isp\",\"ff11\",\"ff22\"]"}
`

2023-05-25 11:07 UTC, awaismslm commented
@UmanShahzad  Do I commit the import break issue on the nested structure in this PR or open a new issue for it?

2023-05-25 16:39 UTC, UmanShahzad commented
```
"type":"[\"hosting\",\"ffff333\",\"ffff4444\"]"
```

Assuming we're doing `-f json`, I'd imagine this should be:

```
"type":["hosting","ffff333","ffff4444"]
```

I think this requires us to treat the `json` output type as a special case. CSV/TSV can remain the original way, because we need to put an actual stringified version of the nested entity into a column, but if we're actually outputting JSON itself, we can make it "real" instead of a wrapped string.

2023-05-26 10:50 UTC, awaismslm commented
@UmanShahzad  I have fixed the `import` on the nested structure, `mmdbctl` is also importing nested structures successfully and the JSON output. Please see the samples below:

**JSON exported using IPinfo's data**:
`{"asn":"AS13335","domain":"cloudflare.com","name":"Cloudflare, Inc.","network":"1.0.0.0/24","range":"1.0.0.0/24","route":"1.0.0.0/24","type":["hosting","ffff333","ffff4444"]}
{"asn":"AS38803","domain":"gtelecom.com.au","name":"Wirefreebroadband Pty Ltd","network":"1.0.4.0/24","range":"1.0.4.0/24","route":"1.0.4.0/22","type":["isp","ff11","ff22"]}
`
**JSON exported using Maxmind's data**:
`{"continent":{"code":"OC","geoname_id":6255151,"names":{"de":"Ozeanien","en":"Oceania","es":"Oceanía","fr":"Océanie","ja":"オセアニア","pt-BR":"Oceania","ru":"Океания","zh-CN":"大洋洲"}},"country":{"geoname_id":2077456,"iso_code":"AU","names":{"de":"Australien","en":"Australia","es":"Australia","fr":"Australie","ja":"オーストラリア","pt-BR":"Austrália","ru":"Австралия","zh-CN":"澳大利亚"}},"network":"1.0.0.0/24","range":"1.0.0.0/24","registered_country":[{"geoname_id":2077456,"iso_code":"AU","names":{"de":"Australien","en":"Australia","es":"Australia","fr":"Australie","ja":"オーストラリア","pt-BR":"Austrália","ru":"Австралия","zh-CN":"澳大利亚"}},{"geoname_id":2077456,"iso_code":"AU","names":{"de":"Australien","en":"Australia","es":"Australia","fr":"Australie22222222222222","ja":"オーストラリア","pt-BR":"Austrália","ru":"Австралия","zh-CN":"澳大利亚"}}]}
`

2023-05-26 12:58 UTC, UmanShahzad reviewed
Thanks a lot @awaismslm , this is looking good as a soluton now. We just need to ensure the code-level solution isn't a hack - just make a new func that does this 'correctly' instead of this.

2023-05-26 12:58 UTC, UmanShahzad commented on cmd_export.go
> +				if strings.Contains(value, "[") && value[0] == '[' { //Check if the value is []interface{}
This is a huge hack - we need to likely build a new func instead of mapInterfaceToStr to do what we want in this special case of json export.

2023-05-29 08:37 UTC, awaismslm commented
@UmanShahzad fixed and tested.

2023-05-29 17:03 UTC, UmanShahzad requested changes
This is still just the hack, moved out to a new func.

2023-05-29 17:04 UTC, UmanShahzad commented
Think of the data flow from scratch for each of the different filetypes, trying to achieve what we wrote above, in a smoother way.

2023-05-30 08:07 UTC, UmanShahzad commented on utils.go
> +		case map[string]interface{}:
We can combine this case and the case below to be the `default` case, so we always JSON marshal instead of doing `fmt.Sprintf("%v", v)`.

2023-05-30 09:58 UTC, awaismslm commented
@UmanShahzad As discussed, It is done and tested.

2023-05-30 10:45 UTC, UmanShahzad approved these changes
We discussed this in person. This is good now but just missing a proper nested approach when going from `json -> mmdb` - right now nested entities there will be turned into JSON string representations in the MMDB which isn't right.

@awaismslm FYI we can't consider the overall issue fixed until the above is fixed.

2023-05-30 10:45 UTC, merged

2023-05-30 11:17 UTC, awaismslm commented
I am opening a new issue on linear for the above.