Fix: Compatibility Issue with IP2Location DB using int for IP Range
ipinfo/mmdbctl pull request #24
Opened 2023-12-04 09:18 UTC by muneebwaqas416

This is the branch of Muneeb Waqas SE Intern

2023-12-04 11:00 UTC, muneebwaqas416 commented
@UmanShahzad Please review this PR.

2023-12-04 11:03 UTC, UmanShahzad requested changes
Still not cleaned up. See your diff

2023-12-04 11:16 UTC, muneebwaqas416 commented
@UmanShahzad Please check it and do let me know if I have done it right or wrong

2023-12-04 11:34 UTC, muneebwaqas416 commented on lib/cmd_import.go
> +
This is not done by me .These lines are in master branch
![Uploading Screenshot 2023-12-04 at 4.33.12 PM.png…]()

2023-12-06 06:53 UTC, muneebwaqas416 commented
@UmanShahzad I have incorporated your feedback in latest commit.

2023-12-06 07:18 UTC, UmanShahzad requested changes

2023-12-06 07:18 UTC, UmanShahzad commented on .gitignore
> +!dist/DEBIAN/
Do return the ending newline

2023-12-06 07:18 UTC, UmanShahzad commented on lib/cmd_import.go
> +
This is still not undone

2023-12-06 07:25 UTC, muneebwaqas416 commented
@UmanShahzad You can check now with feedback incorporated

2023-12-06 07:57 UTC, muneebwaqas416 commented
@UmanShahzad Please review it

2023-12-11 01:42 UTC, UmanShahzad commented
@muneebwaqas416 can you please squash commits n lemme know when this is ready?

2023-12-12 14:56 UTC, UmanShahzad commented
Preferring #26

2023-12-12 14:56 UTC, closed without merging