Addressing issue #17
ipinfo/mmdbctl pull request #26
Opened 2023-12-12 07:03 UTC by shamirShahzad

The IP headers where not being converted to IP string format if the input file was in decimal string format

2023-12-12 07:03 UTC, shamirShahzad commented
@UmanShahzad created as instructed please check

2023-12-12 14:56 UTC, UmanShahzad requested changes

2023-12-12 14:56 UTC, UmanShahzad commented on lib/cmd_import.go
> +func DecimalStrToIP(decimal string) (net.IP, error) {
Can you check if we have some functionality in the IPinfo CLI repo's `lib/` folder that has this logic already? I.e. to convert an int IP into a string IP. If we do, we can do a refactor to allow importing that lib here and using that instead of re-implementing.

2023-12-12 14:56 UTC, UmanShahzad commented on lib/cmd_import.go
> +	if net.ParseIP(decimal) == nil {
Flip the case - if the output isn't nil, then return early with nil results. Otherwise continue with main logic. Reduces indentation and makes code flow clearer.

2023-12-12 14:56 UTC, UmanShahzad commented on lib/cmd_import.go
> +	if start_ip != nil {
Combine into 1 line with the above i.e. `if startIp, _ := DecimalStrToIp(parts[0]); startIp != nil {`

2023-12-12 14:56 UTC, UmanShahzad commented on lib/cmd_import.go
> +	if start_ip != nil {
Also note to use golang style - camel case not snake case.

2023-12-14 04:44 UTC, shamirShahzad commented on lib/cmd_import.go
> +func DecimalStrToIP(decimal string) (net.IP, error) {
Yes we do have a tool called n2ip and n2ip6 both of these use the function DecimalStrToIP to change decimal string ip to string ip format but it is slightly different as it takes as an argument another variable which converts to ipv6 forcibly is that something we want

2023-12-14 06:17 UTC, shamirShahzad commented on lib/cmd_import.go
> +func DecimalStrToIP(decimal string) (net.IP, error) {
@UmanShahzad

2023-12-14 06:18 UTC, UmanShahzad commented on lib/cmd_import.go
> +func DecimalStrToIP(decimal string) (net.IP, error) {
Yeah we wanna use common functionality and try to make it work.

2023-12-18 05:18 UTC, shamirShahzad commented
@UmanShahzad please check if there is something I missed

2023-12-18 06:59 UTC, UmanShahzad approved these changes

2023-12-18 07:00 UTC, merged