added low-level mmdb data to the metadata output
ipinfo/mmdbctl pull request #28
Opened 2023-12-21 09:55 UTC by Taimoor-12

`mmdbctl metadata` output now shows the low-level data of an mmdb file listed in #25.

P.S:
Have incorporated the basic math formulas in our code for now in case this [PR](https://github.com/maxmind/mmdbwriter/pull/76) isn't reviewed or rejected.

2023-12-21 09:56 UTC, Taimoor-12 commented
@UmanShahzad

2023-12-21 13:39 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +	metadataStartMarker = "\xAB\xCD\xEFMaxMind.com"
This is a const no?

2023-12-21 13:41 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +		return errors.New("input valid mmdb file required as first argument")
Flip the condition - `if offset == -1 { return error } ... continue remaining logic at lower indent level`

2023-12-21 13:41 UTC, UmanShahzad commented on lib/cmd_metadata.go
>  	if f.Format == "pretty" {
1 newline above

2023-12-21 13:41 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
Please move it right below tree size

2023-12-21 13:41 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +			DataSectionSize        uint              `json:"data_section_size"`
Below tree size

2023-12-21 13:41 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +			uint(dataSectionSize),
Below tree size

2023-12-22 04:41 UTC, Taimoor-12 commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
I couldn't follow this. Below which tree size should I move these four highlighted lines? There's a variable `treeSize` above. Are you referring to this?

`treeSize := ((int(mdFromLib.RecordSize) * 2) / 8) * int(mdFromLib.NodeCount)`

2023-12-22 08:16 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
Yep asking to reorder vars, and that is the one to move below

2023-12-22 10:23 UTC, UmanShahzad requested changes
Wrong changes were made

2023-12-22 10:23 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +	// Offset of this separator is used to determine the metadata start section, data section end and data section size.
No need to have moved this from where it was

2023-12-22 11:22 UTC, Taimoor-12 commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
Should I move `treeSize` below where the other offsets and data section size are calculated? If I move it, I'll need to adjust the position of `dataSectionStartOffset` as well, as it depends on the value of `treeSize.` 

Additionally, does the order of the print lines (for the pretty format) or the fields in the JSON struct (for the JSON format) need to be changed too or no?

2023-12-22 11:28 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
I was really just talking about the order of printlines, json position, and I guess csv if that's supported. Only the comments I made below

2023-12-22 11:44 UTC, Taimoor-12 commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
Oh got it! Just had one small confusion - should the line that prints tree size be moved at the end or all the four highlighted lines in the comment and in the comments below?

2023-12-22 11:48 UTC, UmanShahzad commented on lib/cmd_metadata.go
> +		printline("Data Section Size", strconv.Itoa(dataSectionSize))
Nah just:

- Tree size
- Data size
- Data sec start offset
- Data sec end offset

2023-12-22 11:56 UTC, UmanShahzad approved these changes

2023-12-22 11:56 UTC, merged