added optional input/output
ipinfo/mmdbctl pull request #6
Opened 2022-08-16 12:30 UTC by rm-Umar

fixes #3

2022-08-16 13:22 UTC, UmanShahzad requested changes

2022-08-16 13:22 UTC, UmanShahzad commented on cmd_import.go
> +		strings.HasSuffix(pflag.Arg(1), ".json") {
There are currently no positional arguments allowed, so if you see `pflag.NArg() == 3`, you can just assume `fIn = pflag.Arg(1)` and `fOut = pflag.Arg(2)`. No need to check suffixes like this.

2022-08-17 05:55 UTC, rm-Umar commented on cmd_import.go
> +		strings.HasSuffix(pflag.Arg(1), ".json") {
We actually had the option of printing the output on `stdout` if `fOut` is empty that's why I went for this approach, if someone provides only the input argument and not the output then it'll not work. So should we restrict users to add the output argument also?

2022-08-17 06:39 UTC, UmanShahzad commented on cmd_import.go
> +		strings.HasSuffix(pflag.Arg(1), ".json") {
Yeah that's good.

2022-08-17 06:49 UTC, UmanShahzad approved these changes

2022-08-17 06:51 UTC, merged